language: node_js
sudo: true
node_js:
  - "node"
  - "8"
before_install:
  - npm install npm@latest -g
before_script:
  - npm run lint
  - npm run test
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: projectap
