version: "3"
services:
  app:
      build: .
      volumes:
        - ./:/app
      working_dir: /app
      environment:
        NODE_ENV: development
      ports:
        - 3000:3000
      command: npm start
volumes:
  - ./AsRunDrop/testFolder:/DropFolder
