version: "3"
services:
  app:
      build: .
      volumes:
        - ./:/app
        - type: bind
          source: ./AsRunDrop/testFolder
          target: /Drop
      working_dir: /app
      environment:
        NODE_ENV: development
      ports:
        - 3000:3000
      command: npm start
