version: "3"
services:
  app:
      build: .
      volumes:
        - ./:/app
      working_dir: /app
      depends_on:
        - mongo
      environment:
        NODE_ENV: development
      ports:
        - 3000:3000
      command: npm start
  mongo:
      image: mongo
      expose:
        - 27017
      volumes:
        - ./data/db:/data/db
  volumes:
    - ./AsRunDrop/testFolder
