'use strict';

const mcsErrorCodes = {
    "151": "Number of switches present in topology relevant to arista.conf = <number of devices>",
    "150": "Number of switches stored in db = <number of devices>",
    "153": "Number of links for device = <deviceId> present in network = <number of links>",
    "152": "Number of links for device = <deviceId> stored in db = <number of links>",
    "155": "Finished streaming",
    "135": "Process Error with finding API VERSION",
    "156": "Reservation percentage can only be set for Ethernet ports/interface-name == 'all' for all Ethernet ports",
    "159": "ERROR: Sender and Receiver port for s:g = <sourceIp:destinationIp> cannot be same sender = <deviceId:port> receiver = <deviceId:port>",
    "158": "ERROR: Device = <deviceId> is not part of current connections set in arista.conf",
    "134": "No API Information available",
    "199": "Interface does not exist on device - missing IntfId",
    "115": "No trackingID for receiver. Using default trackingID A#00000000-0000",
    "114": "FailedReceivers in post",
    "117": "No ValidReceivers to configure in this post",
    "116": "No receiver post data to process",
    "111": "Update SenderDb Failed for senderKey = <senderKey> senderValue = <senderValue> action = <action> trackingID = <trackingID> transactionID = <transactionID> with status = <statusCode>",
    "110": "Bw Update Result = [messages]",
    "113": "Invalid flow-action = <postedAction>. Valid action (To Configure Receivers = addReceivers/ delReceivers, To configure senders = addSenders/ delSenders/ modBw) ",
    "112": "Unavailable sender",
    "177": "TopologyError in StreamIgmp for switchName = <switchName>!",
    "176": "TopologyError in StreamMfib for switchName = <switchName>!",
    "139": "Invalid reservation percentage. Post a valid percentage example:1.0",
    "138": "Invalid Reservation percentage. Valid values should be between 0.0 to 1.0",
    "119": "Sender already added",
    "118": "Unexpected Error <traceback>",
    "165": "No bandwidth information for device = <deviceId:portId>",
    "170": "No PrevNbor info for receiverId = <deviceId> receiverIIF = <portId>",
    "198": "No path diversity",
    "174": "TopologyError in StreamInterfaceDetail for switchName = <switchName>!",
    "183": "Unexpected inIntfID format. Expected <senderMacId>-<port>",
    "160": "ERROR: Spine = <deviceId> is not part of active gRPC connections",
    "175": "TopologyError in StreamLldp for switchName = <switchName>!",
    "180": "Set ingress interface = <portId> of device = <deviceId> is not part of current LLDP . Check link status and lldp.",
    "161": "Device = <deviceId>:<portId> does not have enough bandwidth = bandwidth for action = <flowDirection>",
    "182": "Missing inIntfID",
    "178": "Exception raised in HEARTBEATSTREAM for switchName = <switchName>!",
    "179": "TopologyError in HEARTBEATSTREAM for switchName = <switchName>!",
    "181": "Redis PipeLine Response Error = <error>",
    "186": "Invalid OUI. Enter comma/colon/hyphen separated OUI",
    "171": "Failure to update database with receiver updates = <updateReceiverEntries> action = <receiver action>.  Db Status = <db update status>",
    "184": "Unsupported Port. Use only Ethernet/Vlan port format",
    "185": "FailedSenders in post",
    "163": "Route to Receiver = <deviceId:portId> from sender = <deviceId:portId>cannot be formed for src and destIp sourceIp_destinationIp. ",
    "187": "Invalid endpoint requested",
    "146": "ERROR in setting GRPC update. error = < other gRPC update errors>",
    "147": "failed update to bandwidth = <bw config commands> status = <failstatus>",
    "144": "ERROR in setting GRPC update. error = <_Rendezvous  errors>",
    "145": "No GRPC connectivity to device = <deviceId>. Re-initializing gRPC to configure routes.",
    "142": "Not a configurable Key. Configurable keys = <pollingInterval Keys>",
    "143": "No polling keys to modify",
    "140": "ConfigLib Error:Unable to set pollingInterval for key = <key>",
    "141": "Invalid Polling Interval value. Pass a valid positive Integer>0",
    "148": "Connection error <error message>",
    "149": "Waiting to get LLDP info for device = <deviceId>",
    "120": "Sender already added. stored bandwidth is different for sourceIP = <sourceIP> destinationIP = <destinationIP>. Actual bandwidth = <actualBandwidth>. Use mod-bw action to modify bandwidth",
    "121": "Invalid flow data type. Flow data has to be a list",
    "108": "Posted ModBw for sender same as stored bandwidth. Nothing to Modify",
    "123": "Invalid bandwidth. Set Positive Integer value.",
    "124": "Invalid bandwidth Type <bwType>",
    "125": "<address> Not in Unicast Address RANGE",
    "126": "<address> Not in Multicast Address RANGE",
    "127": "No Source Address present",
    "128": "<address> Missing Unicast octet",
    "129": "No Multicast Address present",
    "166": "Sender = <deviceId> does not have any connections to receiver = <deviceId>",
    "167": "Receiver = <deviceId> does not have any neighbors.",
    "106": "ModBw Failed for sourceIp = <sourceIp>  destinationIp = <destinationIp> inIntfID = <inIntfID>. Sender not added.",
    "107": "ModBw Failed. Sender port is different from stored. Stored senderPort = <stored sender port>",
    "162": "No link available from database between devices <deviceId> and <deviceId>",
    "105": "Deleting Sender <sender post> that was not configured",
    "133": "Invalid inIntfID. No Sender Port present",
    "168": "ConnectionError with DB",
    "173": "WRONGTYPE Operation against a key holding the wrong kind of value",
    "132": "Invalid inIntfID. No Sender MACID present",
    "122": "inIntfID is not the same as stored sender ID = <deviceId>-<port>",
    "131": "Missing Key = <key>",
    "130": "Missing Multicast octet",
    "137": "Invalid Device Id = <deviceId>",
    "164": "Receiver = <deviceId:portId> is not a direct connection or cannot be reached via 1 hop spine. Check if sender and receivers shared spine is visible in network-links",
    "169": "Error in reading <path to db config file>"
}; 
module.exports = mcsErrorCodes;